### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by miaoyongjun** [yanzhenjie/Kalle#3]
04-18 12:49:50.194 2435-2567/pay.com.payment E/AndroidRuntime: FATAL EXCEPTION: Request #1
    Process: xxx.xxx.xxxx, PID: 2435
    java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
        at com.yanzhenjie.kalle.CancelerManager.removeCancel(CancelerManager.java:50)
        at com.yanzhenjie.kalle.simple.RequestManager$2.onEnd(RequestManager.java:101)
        at com.yanzhenjie.kalle.simple.Work.done(Work.java:50)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.set(FutureTask.java:205)
        at java.util.concurrent.FutureTask.run(FutureTask.java:245)
        at com.yanzhenjie.kalle.simple.Work.run(Work.java:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

出现这个错误不频繁  每次请求网络都有可能出现
不单单是指定的一个请求

请求格式如下:
Kalle.post(Urls.IP + Urls.PLAN_LIST)
                    .param("uid", UserUtil.getUid(mContext))
                    .perform(new SimpleCallback<String>() {
                        @Override
                        public void onResponse(SimpleResponse<String, String> response) {
                            ......
                        }
                    });

**Comment by miaoyongjun** [comment]
java.lang.NullPointerException: Attempt to read from field 'com.yanzhenjie.kalle.Request com.yanzhenjie.kalle.CancelerManager$CancelEntity.mRequest' on a null object reference
        at com.yanzhenjie.kalle.CancelerManager$CancelEntity.access$100(CancelerManager.java:74)
        at com.yanzhenjie.kalle.CancelerManager.removeCancel(CancelerManager.java:51)
        at com.yanzhenjie.kalle.simple.RequestManager$2.onEnd(RequestManager.java:101)
        at com.yanzhenjie.kalle.simple.Work.done(Work.java:50)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.set(FutureTask.java:205)
        at java.util.concurrent.FutureTask.run(FutureTask.java:245)
        at com.yanzhenjie.kalle.simple.Work.run(Work.java:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
