### ISSUE TITLE
java.util.concurrent.RejectedExecutionException:

### ISSUE THREAD

**Issue by pengfeigao** [yanzhenjie/Kalle#54]
有个需求请求后台接口返回假设有100条消息，客户端需要调用回执接口将这100条消息置位已收到。但是for循环后，线程池这种情况需要怎么处理？线程池的拒绝策略有必要公开api么？

`2019-04-30 18:07:04.543 9707-9707/com.xxx.imdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.imdemo, PID: 9707
    java.util.concurrent.RejectedExecutionException: Task com.yanzhenjie.kalle.simple.Work@62414e1 rejected from java.util.concurrent.ThreadPoolExecutor@2bfa206[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 8]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
        at com.yanzhenjie.kalle.util.WorkExecutor.execute(WorkExecutor.java:55)
        at com.yanzhenjie.kalle.simple.RequestManager.perform(RequestManager.java:105)
        at com.yanzhenjie.kalle.simple.SimpleBodyRequest$Api.perform(SimpleBodyRequest.java:98)
        at com.xxx.im.net.RestClient.post(RestClient.java:64)
        at com.xxx.im.task.MessageLoopTask.messageReceipt(MessageLoopTask.java:96)
        at com.xxx.im.task.MessageLoopTask.access$100(MessageLoopTask.java:19)
        at com.xxx.im.task.MessageLoopTask$2.onResponse(MessageLoopTask.java:74)
        at com.yanzhenjie.kalle.simple.RequestManager$AsyncCallback$2.run(RequestManager.java:169)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6385)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)`

**Comment by yanzhenjie** [comment]
太凶了吧，一次执行超过128个任务，CPU被占用，其他请求和网络会卡不说，应用性能也会显著下降很多，这种情况应该把这些请求合并起来。比如之前是提交一个ID，那么合并后可以是JsonArray，所有的ID一起提交，让服务端配合一下。
