### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by CaiJingFu** [yanzhenjie/Kalle#59]
2019-05-23 19:08:59.255 29185-29185/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yanzhenjie.kalle.sample, PID: 29185
    java.lang.BootstrapMethodError: Exception from call site #6 bootstrap method
        at okhttp3.internal.Util.<clinit>(Util.java:87)
        at okhttp3.internal.Util.immutableList(Util.java:234)
        at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:127)
        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:482)
        at com.yanzhenjie.kalle.OkHttpConnectFactory.<init>(OkHttpConnectFactory.java:50)
        at com.yanzhenjie.kalle.OkHttpConnectFactory.<init>(OkHttpConnectFactory.java:41)
        at com.yanzhenjie.kalle.OkHttpConnectFactory$Builder.build(OkHttpConnectFactory.java:119)
        at com.yanzhenjie.kalle.sample.App.kalle(App.java:58)
        at com.yanzhenjie.kalle.sample.App.onCreate(App.java:51)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5954)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at okhttp3.internal.Util.<clinit>(Util.java:87) 
        at okhttp3.internal.Util.immutableList(Util.java:234) 
        at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:127) 
        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:482) 
        at com.yanzhenjie.kalle.OkHttpConnectFactory.<init>(OkHttpConnectFactory.java:50) 
        at com.yanzhenjie.kalle.OkHttpConnectFactory.<init>(OkHttpConnectFactory.java:41) 
        at com.yanzhenjie.kalle.OkHttpConnectFactory$Builder.build(OkHttpConnectFactory.java:119) 
        at com.yanzhenjie.kalle.sample.App.kalle(App.java:58) 
        at com.yanzhenjie.kalle.sample.App.onCreate(App.java:51) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5954) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
2019-05-23 19:08:59.316 29218-29218/? E/ctivate.servic: Invalid ID 0x00000000.
2019-05-23 19:08:59.331 28823-29245/? E/Market-ConnectionRSA: get key exception : com.android.org.bouncycastle.util.encoders.DecoderException: unable to decode base64 string: invalid characters encountered in base64 data
2019-05-23 19:08:59.414 29218-29218/? E/ctivate.servic: Invalid ID 0x00000000.
2019-05-23 19:08:59.421 29218-29218/? E/ctivate.servic: Invalid ID 0x00000000.
2019-05-23 19:08:59.448 29218-29218/? E/ctivate.servic: Invalid ID 0x00000000.
2019-05-23 19:08:59.459 29218-29218/? E/ctivate.servic: No package ID 10 found for ID 0x100d00c7.
2019-05-23 19:08:59.459 29218-29218/? E/ctivate.servic: No package ID 10 found for ID 0x100d00c5.
2019-05-23 19:08:59.460 29218-29218/? E/ctivate.servic: Invalid ID 0x00000000.
2019-05-23 19:08:59.597 29497-23308/? E/native: document-store.cc:1429 Failed to update per-doc-data with usage report
2019-05-23 19:08:59.597 29497-23308/? E/native: document-store.cc:1429 Failed to update per-doc-data with usage report
2019-05-23 19:09:10.029 8552-8572/? E/Launcher.AllAppsList: Can't load postion for packageName: com.yanzhenjie.kalle.sample activityName: com.squareup.leakcanary.internal.DisplayLeakActivity
2019-05-23 19:09:36.314 927-1009/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2019-05-23 19:10:36.317 927-1009/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2019-05-23 19:11:36.325 927-1009/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2019-05-23 19:12:36.334 927-1009/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0

**Comment by yanzhenjie** [comment]
是修改了什么东西么，启用Java8就可以了。

**Comment by yanzhenjie** [comment]
No response, close.
