### ISSUE TITLE
Expected Android API level 21+ but was 19

### ISSUE THREAD

**Issue by ttxz** [yanzhenjie/Kalle#61]
你好，在使用okalle库时，由于我最小版本支持为Android  19，所以出现了此错误，看文档说明支持2.3以上，是OkHttp包的问题吗？
`    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:262)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1054)
        at com.yanzhenjie.kalle.OkHttpConnectFactory.<init>(OkHttpConnectFactory.java:50)
        at com.yanzhenjie.kalle.OkHttpConnectFactory.<init>(OkHttpConnectFactory.java:41)
        at com.yanzhenjie.kalle.OkHttpConnectFactory$Builder.build(OkHttpConnectFactory.java:119)
        at com.snbc.atf.MyApplication.onCreate(MyApplication.java:74)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:262) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1054) 
        at com.yanzhenjie.kalle.OkHttpConnectFactory.<init>(OkHttpConnectFactory.java:50) 
        at com.yanzhenjie.kalle.OkHttpConnectFactory.<init>(OkHttpConnectFactory.java:41) 
        at com.yanzhenjie.kalle.OkHttpConnectFactory$Builder.build(OkHttpConnectFactory.java:119) 
        at com.snbc.atf.MyApplication.onCreate(MyApplication.java:74) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
        at dalvik.system.NativeStart.main(Native Method)  ```

Application中初使化代码：

    `   ` KalleConfig httpConfig = KalleConfig.newBuilder()
            .network(new BroadcastNetwork(this))
            .connectionTimeout(20, TimeUnit.SECONDS)
            .readTimeout(20, TimeUnit.SECONDS)
            //            .addInterceptor(new Interceptor() {
            //                @Override
            //                public Response intercept(Chain chain) throws IOException {
            //                    return null;
            //                }
            //            })
            .connectFactory(OkHttpConnectFactory.newBuilder().build())
            .addInterceptor(new LoggerInterceptor("HTTP", true))
            .build();

        Kalle.setConfig(httpConfig); `

使用：

     `    ` Kalle.get("...")
            .path("...")
            .path("路径")
            .perform(new SimpleCallback<String>() {
                AlertDialog dialog;
                @Override
                public void onStart() {
                    Log.i("@@@", "开始请求...");
                    dialog = new AlertDialog.Builder(MainActivity.this)
                        .setMessage("正在加载，请稍候...")
                        .show();
                }

                @Override
                public void onResponse(SimpleResponse<String, String> response) {
                    Log.i("@@@", "请求成功-->" + response.succeed());
                }

                @Override
                public void onException(Exception e) {
                    Log.i("@@@","请求失败-->", e);
                }

                @Override
                public void onCancel() {
                    Log.i("@@@", "请求取消-->");
                }

                @Override
                public void onEnd() {
                    Log.i("@@@", "请求结束-->");
                    dialog.dismiss();
                }
            });  `

在此谢过。

**Comment by yanzhenjie** [comment]
[https://github.com/square/okhttp/issues/4622](https://github.com/square/okhttp/issues/4622)
