### ISSUE TITLE
我在批量下载文件的时候，遇到 Could not allocate CursorWindow 错误

### ISSUE THREAD

**Issue by shaoweijin** [yanzhenjie/Kalle#93]
E/CursorWindow: Could not allocate CursorWindow '/data/user/0/com.launchso.qkm.reg/databases/_kalle_cookies_db.db' of size 2097152 due to error -12.
E/DownloadCallback:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, com.launchso.qkm.net.http.DownloadCallback.onException(DownloadCallback.java:60)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
    │ 	at android.database.CursorWindow.<init>(CursorWindow.java:108)
    │ 	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
    │ 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
    │ 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
    │ 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
    │ 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
    │ 	at com.yanzhenjie.kalle.cookie.db.CookieDao.getList(CookieDao.java:186)
    │ 	at com.yanzhenjie.kalle.cookie.db.CookieDao.getList(CookieDao.java:144)
    │ 	at com.yanzhenjie.kalle.cookie.DBCookieStore.get(DBCookieStore
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/DownloadCallback:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ .java:109)
    │ 	at com.yanzhenjie.kalle.cookie.CookieManager.get(CookieManager.java:47)
    │ 	at com.yanzhenjie.kalle.connect.http.ConnectInterceptor.connect(ConnectInterceptor.java:120)

**Comment by shaoweijin** [comment]
Kalle.getConfig().getCookieStore().clear();
我在遍历过程中，过段时间执行一次上面的清cookie的方法后，程序就没有出现异常了
